import type { Metadata } from "next";
import { Montserrat, Bonheur_Royale, Anton } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--font-montserrat",
  display: "swap",
});

const bonheurRoyale = Bonheur_Royale({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-bonheur-royale",
  display: "swap",
});

const anton = Anton({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-anton",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
        ${montserrat.variable}
        ${bonheurRoyale.variable}
        ${anton.variable}
        antialiased
        `}
      >
        <div className="w-full min-h-screen overflow-x-hidden">{children}</div>
      </body>
    </html>
  );
}
